import re
import os

views_template_path = 'sql/views/views_template.sql'
placeholder_pattern = re.compile(r'{{ (.*) }}')

with open(views_template_path) as f:
    views_template = f.read()

placeholder_matches = placeholder_pattern.finditer(views_template)
filepaths = []
for placeholder_match in placeholder_matches:
    filepath = placeholder_match.groups()[0]
    filepaths.append(filepath)

for filepath in filepaths:
    with open(filepath) as f:
        content_to_inject = f.read()
    content_placeholder_pattern = re.compile(r'{{ ' + filepath + ' }}')
    views_template = content_placeholder_pattern.sub(content_to_inject, views_template)

views_template = '-- FILE AUTOGENERATED BY {}\n'.format(__file__) + views_template

with open('sql/views/views.sql', 'w') as f:
    f.write(views_template)
